version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
    assignees:
      - "Addono"
    commit-message:
      prefix: "feat(deps):"
    ignore:
      - dependency-name: "ghcr.io/zhliau/fika-spt-server-docker"
        versions: [">= 4"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "GitHub Actions"
    assignees:
      - "Addono"
    commit-message:
      prefix: "ci(deps):"
