app = '<SERVER_NAME>'

primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
## Disabled as to allow suspending the server, which leads to faster boots. Re-enable when 
## going out of memory and not wanting to provision a larger server.
# swap_size_mb = 1024  ## Mutually exclusive with auto_stop_machines in "suspend"-mode

[build]
  dockerfile = "Dockerfile"

[env]
  UID = '1000'
  GID = '1000'
  TZ = 'Europe/Berlin'
  INSTALL_FIKA = 'true'
  FIKA_VERSION = 'v2.4.6'
  AUTO_UPDATE_SPT = 'true'
  AUTO_UPDATE_FIKA = 'true'
  TAKE_OWNERSHIP = 'true'
  ENABLE_PROFILE_BACKUPS = 'true'
  LISTEN_ALL_NETWORKS = 'true'
  INSTALL_OTHER_MODS = 'true'
  MOD_URLS_TO_DOWNLOAD = '''
  https://github.com/c-orter/ModSync/releases/download/v0.11.1/Corter-ModSync-v0.11.1.zip
  https://github.com/project-fika/Fika-Plugin/releases/download/v1.2.6/Fika.Release.1.2.6.0.zip
  https://github.com/project-fika/Fika-Headless/releases/download/v1.3.5/Fika.Headless.1.3.5.zip

  https://github.com/VirtualAE/Virtuals-Custom-Quest-Loader/releases/download/2.0.4/VCQL-2.0.4.zip
  https://github.com/LunaAufLock/LotusTrader/releases/download/v1.5.2/Lotus_v1.5.2_for_SPT_3.11_by_Lunnayaluna.7z

  https://github.com/GhostFenixx/SVM/releases/download/v1.11.1/SVM.Server.Value.Modifier1.11.1.zip
  
  https://github.com/tyfon7/UIFixes/releases/download/v4.1.2/Tyfon-UIFixes-4.1.2.zip
  https://github.com/CWXDEV/Kaeno-TraderScrolling/releases/download/1.2.0/Kaeno-TraderScrolling.-.1.2.0.zip
  https://github.com/TadMaj/Tarkov-QuickSell/releases/download/2.1.0/Quicksell-2.1.0.zip
  https://drive.usercontent.google.com/download?id=1KJRRXNaolsxcqBgmxlU0SWaJRGml6RHy&export=download&authuser=0
  https://github.com/Markosz22/StashManagementHelper/releases/download/v0.1.5/StashManagementHelper.0.1.5.7z
  https://github.com/danx91/AllQuestsCheckmarks/releases/download/v1.2.3/allquestscheckmarks-1.2.3-spt-3.11.zip
  https://github.com/peinwastaken/shadowflickerfix/releases/download/1.0.5/shadowflickerfix.zip
  https://github.com/CJ-SPT/StashSearch/releases/download/V1.4.1/StashSearch.7z
  https://github.com/CJ-SPT/Expanded-Task-Text/releases/download/V1.6.3/ExpandedTaskText.7z

  https://github.com/DrakiaXYZ/SPT-Waypoints/releases/download/1.7.0/DrakiaXYZ-Waypoints-1.7.0.7z
  https://github.com/Skwizzy/SPT-LootingBots/releases/download/v1.5.2-spt-3.11/Skwizzy-LootingBots-1.5.2.zip
  https://github.com/Lacyway/NerfBotGrenades/releases/download/v1.1/NerfBotGrenades.zip
  https://github.com/acidphantasm/acidphantasm-apbs/releases/download/1.8.2/acidphantasm-progressivebotsystem.zip
  https://github.com/acidphantasm/acidphantasm-defaultfiremode/releases/download/1.3.0/acidphantasm-defaultfiremode.zip
  https://github.com/Lacyway/HandsAreNotBusy/releases/download/1.5/HandsAreNotBusy.zip
  https://github.com/Lacyway/ContinuousHealing/releases/download/v1.3.0/ContinuousHealing.zip
  https://github.com/IhanaMies/HealingAutoCancel/releases/download/4.0.0/IhanaMies-HealingAutoCancel-400.7z
  '''

# https://github.com/ekky-llc/spt-raid-review/releases/download/v0.3.0/raid_review__0.3.0_linux.tar.gz
# 
#  

[[mounts]]
  source = 'spt'
  destination = '/opt/server'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "3GB"


[http_service]
  internal_port = 6969
  force_https = false
  auto_start_machines = true
  auto_stop_machines = "suspend"  # Only available when not using swap
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]


[services]
  internal_port = 6969
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 6969

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2
