name: Backup Profiles

on:
  workflow_dispatch:  # Manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Backup and download profiles
        run: |
          # Make sure at least one machine is running
          MACHINE_ID=$(flyctl machine list --json | jq ".[0].id" -r)
          flyctl machine start $MACHINE_ID
          
          # SSH into the machine to create a 7z archive in /tmp
          flyctl ssh console -C "7zz a /tmp/profiles.7z /opt/server/user/profiles/"
          
          # Download the 7z file
          echo "get /tmp/profiles.7z" | flyctl sftp shell
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload profiles as artifact
        uses: actions/upload-artifact@v4
        with:
          name: profiles-backup-${{ steps.date.outputs.date }}
          path: profiles.7z
          retention-days: 30  # Keep backups for a month
