name: Deploy to Fly.io
on:
  workflow_dispatch:  # Manual triggering
  
jobs:
  deploy:
    name: Deploy app
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
